### ISSUE TITLE
Express 5 heads up

### ISSUE THREAD

**Issue by kswope** [continuationlabs/celebrate#42] opened 2017-11-01 06:43 UTC
```
Cannot set property query of #<IncomingMessage> which has only a getter

TypeError: Cannot set property query of #<IncomingMessage> which has only a getter
    at Joi.validate (/home/kevin/wheatt-node/node_modules/celebrate/lib/index.js:37:23)
```

Commenting out that line seemed to fix the problem, if that helps. Not sure what it does.

**Comment by arb** [comment] 2017-11-01 16:33
Hmmm interesting. Seems like we're going to need to do some extra now to update incoming message values when Joi makes changes to the object.

Are there docs about Express 5 anywhere?

**Comment by kswope** [comment] 2017-11-01 18:28
I've only found this
http://expressjs.com/en/guide/migrating-5.html

Why is it that I could comment out the offending line and seemingly make it work again?

**Comment by cjihrig** [comment] 2017-11-01 18:33
> Why is it that I could comment out the offending line and seemingly make it work again?

Are you referring to https://github.com/continuationlabs/celebrate/blob/a61daa15813f828515bbbedd33bea989f32b59eb/lib/index.js#L37? If so, it works because you're no longer overwriting the existing `query` mentioned in that error message. The problem is that it cripples the functionality of Celebrate. You will be able to validate inputs, but not update them, which is something Joi supports.

**Comment by kswope** [comment] 2017-11-01 19:02
Oh ok I didn't realize Joi had that 'convert' option, now it makes sense.

I vaguely remember req.params changing to read only, but I can't remember where.  I can understand the argument that middleware shouldn't be modifying the input, but I think you have a stronger argument.  I'm dig a little deeper into this.

**Comment by cjihrig** [comment] 2017-11-01 19:07
For context:

Here is the Express 5.0 release notes/PR: https://github.com/expressjs/express/pull/2237
Here is the PR that updated `req.query` to be a getter: https://github.com/expressjs/express/issues/2215
Here is the commit: https://github.com/expressjs/express/pull/2237/commits/dcc4eaabe86a4309437db2a853c5ef788a854699

**Comment by kswope** [comment] 2017-11-01 19:36
That commit is over 3 years old, somebody tell these guys to slow the heck down.

**Comment by cjihrig** [comment] 2017-11-03 20:50
If anyone is following along here, and cares enough, there is some discussion going on at https://github.com/expressjs/express/issues/3472. You may want to weigh in.

**Comment by arb** [comment] 2017-11-07 18:58
Closed via https://github.com/continuationlabs/celebrate/pull/48

**Closed by arb** 2017-11-07 18:58 UTC
